---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resourceNames:
  - annotation-scheduler-audit-config
  - annotation-scheduler-security-config
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.sandbox.davcgar.aws
  resources:
  - annotationschedulerules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.sandbox.davcgar.aws
  resources:
  - annotationschedulerules/finalizers
  verbs:
  - update
- apiGroups:
  - scheduler.sandbox.davcgar.aws
  resources:
  - annotationschedulerules/status
  verbs:
  - get
  - patch
  - update
