apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- security-config.yaml

namespace: system

commonLabels:
  app.kubernetes.io/name: dynamic-annotation-controller
  app.kubernetes.io/component: security